name: BirthdayPipeline
run-name: BirthdayPipeline for CP Team 🚀
on: 
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl
          pip install pandas

      - name: Call Script
        id: callscript
        run: |
          birthdaymessage=$(python scripts/BirthdayChecker.py)

      - name: Count Files
        id: count_files
        run: |
          directory_count=$(ls templates/ | wc -l)
          echo "::set-output name=directory_count::$directory_count"

      - name: Send email
        if: ${{ steps.count_files.outputs.directory_count > 1}}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.EMAIL_ID}}
          password: ${{secrets.PASSWORD}}
          subject: Reminder to Celebrate Birthday
          html_body:  file://templates/birthdaytemplatereplaced.html
          to: cp_team@hpe.com
          from: Birthday Reminder
