name: BirthdayPipeline
run-name: BirthdayPipeline for CP Team 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.Call_Script.outputs }}
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Call_Script
        run: python scripts/BirthdayChecker.py

