name: BirthdayPipeline
run-name: BirthdayPipeline for CP Team 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl
          pip install pandas

      - name: Call_Script
        run: birthday_dict=$(python scripts/BirthdayChecker.py)

      - name: Checking
        run: echo "num=3" >> $GITHUB_OUTPUT

      - name: Print_Output
        run: echo "num value is ${{ steps.Checking.outputs.num }}"

