name: BirthdayPipeline
run-name: BirthdayPipeline for CP Team 🚀
on: [push]
jobs:
  build:
    outputs:
      message: ${{ steps.callscript.outputs.birthdaymessage }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl
          pip install pandas

      - name: Call Script
        id: callscript
        run: echo "birthdaymessage=$(python scripts/BirthdayChecker.py)" >> $GITHUB_OUTPUT

  sendemail:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.message != '' }}
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.EMAIL_ID}}
          password: ${{secrets.PASSWORD}}
          subject: Birthday Reminder
          body: ${{ needs.build.outputs.message }}
          to: swetha6530@gmail.com
          from: Swetha Swaminathan
